### ISSUE TITLE
Self-Recharging Wallet (SRW)

### ISSUE THREAD

**Issue by SKALE-jace** [skalenetwork/skale-manager#821]
*Validators had 1 ETH in their wallet,
*Wallet is supposed to self charge from SRW but it reduced to 0.8.
*Now they have to top up manually each wallet, and is it's expensive. 

{will be adding more info}

**Comment by payvint** [comment]
Will consist "NodeRefundedByValidator" event also

**Comment by yavrsky** [comment]
The solution that was provided in the PR above separates the gas reimbursement logic a bit. That keeps the old mechanism of gas reimbursement for chain operations and change it for operations that causes by nodes itself. In this way nothing will change in gas reimbursement for broadcast and alright. Gas refunds for validator operations will work this way. A certain value will be set, which will meet the minimum amount of ether on the node. After each operation, we will return not the either that spent, but the modulus of the difference between the current value and the minimum required amount of ether on the node. Thus, the amount of gas on all nodes will be aligned with this value (in fact, this value will be slightly less, because after the difference is compensated, gas will be spent on the node for the execution of the transaction).

**Comment by yatsunastya** [comment]
Checked. [Results](https://skaleqa.testrail.io/index.php?/runs/view/157&group_by=cases:section_id&group_order=asc&group_id=17)
This [issue](https://github.com/skalenetwork/internal-support/issues/331) is fixed here.

**Comment by DimaStebaev** [comment]
[1.9.3-beta.0](https://github.com/skalenetwork/skale-manager/releases/tag/1.9.3-beta.0)

**Comment by yatsunastya** [comment]
Checked.
Skale Manager version: 1.9.3-beta.3
You can find results in TestRail - Node Rotation - SRW 2.1 Release
